"""Vault Master Data Key (MDK) derivation for the manual unseal mode.

Security model
--------------
The MDK-wrapping key is derived from the *password component* of the
**admin/superuser DSN** (``$DATABASE_URL_SUPER`` or ``$DATABASE_URL_ADMIN``)
plus a random salt stored in ``system_meta.unseal_salt``.

This design deliberately collapses the security boundary to
"protect ``$DATABASE_URL``".  The threat it guards against is a
**cold-storage leak**: if someone obtains a database volume backup or
pg_dump without the live ``$DATABASE_URL``, they cannot decrypt the
secrets stored in ``10_fct_secrets``.

It does NOT protect against an attacker who already has ``$DATABASE_URL``
— that attacker can connect directly and read anything the write role
can read. Vault encryption is an additional layer, not a substitute for
securing the connection string.

For production-grade key management, switch to the Azure KMS unseal mode
(or AWS/GCP KMS when those backends land). Manual mode is designed for
single-VM deployments and local development.

Derivation algorithm
--------------------
1. Argon2id (time_cost=3, memory_cost=64MiB, parallelism=1, hash_len=32):
   ``intermediate = Argon2id(secret=password, salt=salt)``
   Argon2id slows down brute-force attacks against weak DB passwords
   (e.g. docker-compose defaults).  For the strong random passwords
   generated by Mode A the KDF is redundant but harmless.

2. HKDF-SHA256 (length=32, info=``b"tennetctl/mdk-wrap/v1"``):
   ``wrap_key = HKDF(ikm=intermediate, info=...)``
   HKDF pins the derivation *version* via the ``info`` string.  If the
   algorithm ever changes, bump to ``b"tennetctl/mdk-wrap/v2"`` so the
   old wrap_key is never accidentally reused with the new algorithm.

Rotating the database password
--------------------------------
Changing the password on ``$DATABASE_URL`` without re-wrapping the MDK
will cause the ``unseal_key_hash`` check to fail on the next boot.
A future ``tennetctl vault rotate-unseal-key`` command handles this; it
re-derives the new wrap_key and re-encrypts the MDK ciphertext stored in
``10_fct_vault``.

Version
-------
``info=b"tennetctl/mdk-wrap/v1"``  — never change this string.  Create a
v2 constant instead and migrate rows.
"""

from __future__ import annotations

import hashlib
import secrets

from argon2.low_level import ARGON2_VERSION, Type, hash_secret_raw
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

_HKDF_INFO = b"tennetctl/mdk-wrap/v1"
_ARGON2_TIME_COST = 3
_ARGON2_MEMORY_COST = 65536  # 64 MiB
_ARGON2_PARALLELISM = 1
_ARGON2_HASH_LEN = 32
_SALT_LEN = 16  # bytes


def new_salt() -> bytes:
    """Return 16 cryptographically random bytes for use as the Argon2 salt."""
    return secrets.token_bytes(_SALT_LEN)


def derive_wrap_key(password: str, salt: bytes) -> bytes:
    """Derive the 32-byte AES-256 key used to wrap the vault MDK.

    Args:
        password: The password component of ``$DATABASE_URL``.
        salt:     The 16-byte random salt stored in ``system_meta.unseal_salt``.

    Returns:
        A 32-byte key suitable for AES-256-GCM encryption of the MDK.
        The same (password, salt) pair always produces the same key.
    """
    intermediate: bytes = hash_secret_raw(
        secret=password.encode("utf-8"),
        salt=salt,
        time_cost=_ARGON2_TIME_COST,
        memory_cost=_ARGON2_MEMORY_COST,
        parallelism=_ARGON2_PARALLELISM,
        hash_len=_ARGON2_HASH_LEN,
        type=Type.ID,
        version=ARGON2_VERSION,
    )
    return HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=None,
        info=_HKDF_INFO,
    ).derive(intermediate)


def blake2b_hex(data: bytes) -> str:
    """Return a 64-character hex-encoded BLAKE2b-256 digest of *data*.

    Stored in ``10_fct_vault.unseal_key_hash`` so the runtime can verify
    it derived the correct wrap_key before attempting AES-GCM decryption.
    """
    return hashlib.blake2b(data, digest_size=32).hexdigest()
