-- =============================================================================
-- Migration: 20260408_004_vault_secrets_fct.sql
-- Module:    02_vault
-- Sub-feature: 01_setup
-- Sequence:  004
-- Description: Pure-EAV secret storage for the vault module.
--              Creates 02_vault.10_fct_secrets as a lean fct_* identity table
--              (no wide columns). path, ciphertext, nonce live in 20_dtl_attrs
--              via attr_defs seeded in migration 001 (ids 16, 17, 18).
--              Uniqueness on path is enforced by a partial index on 20_dtl_attrs.
--              Depends on: 001 (bootstrap: schema + EAV tables + attr_defs).
-- =============================================================================

-- UP =========================================================================

-- ---------------------------------------------------------------------------
-- 10_fct_secrets
-- Pure-EAV identity table. One row per named secret.
-- All business data (path, ciphertext, nonce) lives in 20_dtl_attrs.
--
-- Encryption model (envelope encryption):
--   plaintext_value
--       ↓  AES-256-GCM(key=MDK, nonce=random_12_bytes, aad=path)
--   ciphertext  +  nonce
--
-- The MDK (Master Data Key) is held in process memory after the vault
-- is unsealed. It is never persisted in plaintext anywhere.
-- ---------------------------------------------------------------------------
CREATE TABLE "02_vault"."10_fct_secrets" (
    id          VARCHAR(36)  NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    is_test     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP,
    created_by  VARCHAR(36),
    updated_by  VARCHAR(36),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_02vault_fct_secrets PRIMARY KEY (id)
);

COMMENT ON TABLE "02_vault"."10_fct_secrets" IS
    'Pure-EAV identity table for vault secrets. '
    'Holds only UUID identity + housekeeping columns. '
    'path, ciphertext, and nonce are stored in 20_dtl_attrs (attr_def ids 16–18). '
    'Uniqueness on path is enforced by a partial index on 20_dtl_attrs. '
    'The MDK required to decrypt lives only in process memory after unsealing.';

COMMENT ON COLUMN "02_vault"."10_fct_secrets".id IS
    'UUID v7 primary key. Generated by the application.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".is_active IS
    'FALSE = logically disabled. Reads are rejected for inactive secrets.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".is_test IS
    'TRUE = row was created by a test fixture. Excluded from production reads.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".deleted_at IS
    'Soft-delete timestamp. NULL = live. Non-NULL = deleted.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".created_by IS
    'UUID v7 of the actor (user or system installer) that created this row.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".updated_by IS
    'UUID v7 of the actor that last updated this row.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".created_at IS
    'Row creation timestamp (UTC).';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".updated_at IS
    'Last update timestamp (UTC). Updated by trigger in later migrations; '
    'defaults to created_at at insert.';

GRANT SELECT ON "02_vault"."10_fct_secrets" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE ON "02_vault"."10_fct_secrets" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- Partial unique index on path attr value in 20_dtl_attrs.
-- Enforces: only one live path value per secret (across all secrets).
-- Resolved dynamically so this survives identity shifts across environments.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    path_attr_id SMALLINT;
    secret_et_id SMALLINT;
BEGIN
    SELECT id INTO secret_et_id FROM "02_vault"."06_dim_entity_types" WHERE code = 'secret';
    SELECT id INTO path_attr_id  FROM "02_vault"."07_dim_attr_defs"   WHERE entity_type_id = secret_et_id AND code = 'path';
    EXECUTE format(
        'CREATE UNIQUE INDEX uq_02vault_dtl_attrs_secret_path '
        'ON "02_vault"."20_dtl_attrs" (key_text) '
        'WHERE attr_def_id = %s AND key_text IS NOT NULL',
        path_attr_id
    );
END $$;

-- ---------------------------------------------------------------------------
-- v_secrets
-- Read view — exposes metadata + path. Deliberately excludes ciphertext/nonce.
-- Safe to include in API responses and log output.
-- path is pivoted from EAV via correlated subquery.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW "02_vault"."v_secrets" AS
SELECT
    s.id,
    (
        SELECT da.key_text
          FROM "02_vault"."20_dtl_attrs" da
          JOIN "02_vault"."07_dim_attr_defs" ad
            ON ad.id = da.attr_def_id
         WHERE da.entity_id = s.id
           AND ad.code = 'path'
         LIMIT 1
    ) AS path,
    s.is_active,
    s.is_test,
    s.deleted_at,
    s.created_by,
    s.updated_by,
    s.created_at,
    s.updated_at
FROM "02_vault"."10_fct_secrets" s;

COMMENT ON VIEW "02_vault"."v_secrets" IS
    'Read-safe view of the secrets table. '
    'Pivots path from EAV (20_dtl_attrs). '
    'Excludes ciphertext and nonce — the only view safe to include in API responses.';

GRANT SELECT ON "02_vault"."v_secrets" TO tennetctl_read;
GRANT SELECT ON "02_vault"."v_secrets" TO tennetctl_write;

-- DOWN =======================================================================

DROP VIEW IF EXISTS "02_vault"."v_secrets";
DROP INDEX IF EXISTS "02_vault".uq_02vault_dtl_attrs_secret_path;
DROP TABLE IF EXISTS "02_vault"."10_fct_secrets";
