-- =============================================================================
-- Migration: 20260408_004_vault_secrets_fct.sql
-- Module:    02_vault
-- Sub-feature: 01_setup
-- Sequence:  004
-- Description: Envelope-encrypted secret storage for the vault module.
--              Creates 02_vault.10_fct_secrets to hold AES-256-GCM ciphertext
--              and nonce for each named secret. Paths are unique (per active row).
--              Depends on: 002 (vault schema + 10_fct_vault must exist).
-- =============================================================================

-- UP =========================================================================

-- ---------------------------------------------------------------------------
-- 10_fct_secrets
-- One row per named secret. Each row stores the AES-256-GCM ciphertext of
-- the plaintext value plus the 12-byte nonce used during encryption.
--
-- Encryption model (envelope encryption):
--   plaintext_value
--       ↓  AES-256-GCM(key=MDK, nonce=random_12_bytes, aad=path)
--   ciphertext  +  nonce
--
-- The MDK (Master Data Key) is held in process memory after the vault
-- is unsealed. It is never persisted in plaintext anywhere.
--
-- The 'path' column is the AAD (associated data) passed to AES-256-GCM.
-- This binds ciphertext to its canonical path: moving ciphertext to a
-- different path row causes decryption to fail with an authentication error.
--
-- Standard fct_* columns apply: soft-delete via deleted_at, is_test for
-- fixture rows, is_active for logical state.
-- ---------------------------------------------------------------------------
CREATE TABLE "02_vault"."10_fct_secrets" (
    id          VARCHAR(36)  NOT NULL,
    path        TEXT         NOT NULL,
    ciphertext  TEXT         NOT NULL,
    nonce       TEXT         NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    is_test     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMP,
    created_by  VARCHAR(36),
    updated_by  VARCHAR(36),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_02vault_fct_secrets PRIMARY KEY (id)
);

-- Partial unique index: only one live row per path.
-- Soft-deleted rows (deleted_at IS NOT NULL) are excluded so the same path
-- can be re-created after deletion.
CREATE UNIQUE INDEX uq_02vault_fct_secrets_path_active
    ON "02_vault"."10_fct_secrets" (path)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_02vault_fct_secrets_path
    ON "02_vault"."10_fct_secrets" (path);

CREATE INDEX idx_02vault_fct_secrets_created_at
    ON "02_vault"."10_fct_secrets" (created_at DESC);

COMMENT ON TABLE "02_vault"."10_fct_secrets" IS
    'Envelope-encrypted secrets store. One active row per path. '
    'ciphertext and nonce hold the AES-256-GCM output; the path is the AAD '
    '(associated data) so ciphertext is bound to its canonical path. '
    'The MDK required to decrypt lives only in process memory after unsealing — '
    'it is never persisted here or in any other table.';

COMMENT ON COLUMN "02_vault"."10_fct_secrets".id IS
    'UUID v7 primary key. Generated by the application.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".path IS
    'Slash-separated logical path identifying this secret, e.g. '
    '"tennetctl/db/write_dsn". Unique among live (non-deleted) rows. '
    'Also used as AES-256-GCM associated data (AAD) — changing the path '
    'of an existing ciphertext will cause decryption to fail.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".ciphertext IS
    'Base64url-encoded AES-256-GCM ciphertext of the plaintext secret value. '
    'Encrypted with the MDK. The AAD is the UTF-8 encoding of the path column.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".nonce IS
    'Base64url-encoded 12-byte GCM nonce used during encryption. '
    'Must be unique per (secret, encryption event). Never reuse.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".is_active IS
    'FALSE = logically disabled. Reads are rejected for inactive secrets. '
    'Updated by application logic, not by soft-delete.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".is_test IS
    'TRUE = row was created by a test fixture. Excluded from production reads.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".deleted_at IS
    'Soft-delete timestamp. NULL = live. Non-NULL = deleted; excluded from the '
    'partial unique index so the same path can be re-created.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".created_by IS
    'UUID v7 of the actor (user or system installer) that created this row.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".updated_by IS
    'UUID v7 of the actor that last updated this row.';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".created_at IS
    'Row creation timestamp (UTC).';
COMMENT ON COLUMN "02_vault"."10_fct_secrets".updated_at IS
    'Last update timestamp (UTC). Updated by trigger in later migrations; '
    'defaults to created_at at insert.';

GRANT SELECT ON "02_vault"."10_fct_secrets" TO tennetctl_read;
GRANT SELECT, INSERT, UPDATE, DELETE ON "02_vault"."10_fct_secrets" TO tennetctl_write;

-- ---------------------------------------------------------------------------
-- v_secrets
-- Read view — exposes metadata only. Deliberately excludes ciphertext and nonce.
-- Safe to include in API responses and log output.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW "02_vault"."v_secrets" AS
SELECT
    id,
    path,
    is_active,
    is_test,
    deleted_at,
    created_by,
    updated_by,
    created_at,
    updated_at
FROM "02_vault"."10_fct_secrets";

COMMENT ON VIEW "02_vault"."v_secrets" IS
    'Read-safe view of the secrets table. '
    'Excludes ciphertext and nonce — the only view safe to include in API responses.';

GRANT SELECT ON "02_vault"."v_secrets" TO tennetctl_read;
GRANT SELECT ON "02_vault"."v_secrets" TO tennetctl_write;

-- DOWN =======================================================================

DROP VIEW IF EXISTS "02_vault"."v_secrets";
DROP TABLE IF EXISTS "02_vault"."10_fct_secrets";
